CREATE TABLE FEDERACAO (
    NOME VARCHAR(30),
    ID_FED INT,
    CONSTRAINT PK_FEDERACAO PRIMARY KEY (ID_FED)
);

CREATE TABLE PRESIDENTE_DA_FEDERACAO (
    NOME VARCHAR(30),
    ID INT,
    ID_FED INT,
    CONSTRAINT PK_PRESIDENTE_DA_FEDERACAO PRIMARY KEY (ID),
    CONSTRAINT FK_PRESIDENTE_FEDERACAO FOREIGN KEY (ID_FED) REFERENCES FEDERACAO(ID_FED)
);

--edição