----------------------
-- POVOAMENTO DO BD --
----------------------

--Federacoes:
INSERT INTO FEDERACAO VALUES ('CBF', 1010); -- Brasil
INSERT INTO FEDERACAO VALUES ('AFA', 0420); -- Argentina
INSERT INTO FEDERACAO VALUES ('FPF', 0001); -- Pernambuco
INSERT INTO FEDERACAO VALUES ('CONMEBOL', 0002); -- America do Sul
INSERT INTO FEDERACAO VALUES ('UEFA', 0003); -- Europa
INSERT INTO FEDERACAO VALUES ('RFEF', 0004); -- Espanha
INSERT INTO FEDERACAO VALUES ('FA', 0005); -- Inglaterra
INSERT INTO FEDERACAO VALUES ('FFF', 1919); -- França
INSERT INTO FEDERACAO VALUES ('DFB', 2121); -- Alemanha
INSERT INTO FEDERACAO VALUES ('FIGC', 1111); -- Italia
INSERT INTO FEDERACAO VALUES ('FIFA', 0000); -- Mundo


--Presidente da Federacao:
INSERT INTO PRESIDENTE_DA_FEDERACAO VALUES ('Ednaldo Rodrigues', 0001, 1010); -- Brasil
INSERT INTO PRESIDENTE_DA_FEDERACAO VALUES ('Claudio "Chiqui" Fabián Tapia', 0002, 0420); -- Argentina
INSERT INTO PRESIDENTE_DA_FEDERACAO VALUES ('Evandro Barros', 0003, 0001); -- Pernambuco
INSERT INTO PRESIDENTE_DA_FEDERACAO VALUES ('Alejandro Domínguez', 0004, 0002); -- America do Sul
INSERT INTO PRESIDENTE_DA_FEDERACAO VALUES ('Aleksander Ceferin', 0005, 0003); -- Europa
INSERT INTO PRESIDENTE_DA_FEDERACAO VALUES ('Luis Rubiales', 0006, 0004); -- Espanha
INSERT INTO PRESIDENTE_DA_FEDERACAO VALUES ('Debbie Hewitt', 0007, 0005); -- Inglaterra
INSERT INTO PRESIDENTE_DA_FEDERACAO VALUES ('Philippe Diallo', 0008, 1919); -- Franca
INSERT INTO PRESIDENTE_DA_FEDERACAO VALUES ('Bernd Neuendorf', 0009, 2121); -- Alemanha
INSERT INTO PRESIDENTE_DA_FEDERACAO VALUES ('Gabriele Gravina', 0010, 1111); -- Italia
INSERT INTO PRESIDENTE_DA_FEDERACAO VALUES ('Gianni Infantino', 0011, 0000); -- Mundo

--Estadio:
INSERT INTO ESTADIO VALUES ();
INSERT INTO ESTADIO VALUES ();
INSERT INTO ESTADIO VALUES ();
INSERT INTO ESTADIO VALUES ();
INSERT INTO ESTADIO VALUES ();
INSERT INTO ESTADIO VALUES ();
INSERT INTO ESTADIO VALUES ();
INSERT INTO ESTADIO VALUES ();
INSERT INTO ESTADIO VALUES ();
INSERT INTO ESTADIO VALUES ();
INSERT INTO ESTADIO VALUES ();
INSERT INTO ESTADIO VALUES ();
INSERT INTO ESTADIO VALUES ();
INSERT INTO ESTADIO VALUES ();
INSERT INTO ESTADIO VALUES ();
INSERT INTO ESTADIO VALUES ();
INSERT INTO ESTADIO VALUES ();


